# Generated by Django 5.0.7 on 2025-06-16 10:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngojsct_mlm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('slip_for', models.CharField(max_length=50)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngojsct_mlm.membermodel')),
            ],
            options={
                'db_table': 'tbl_donation',
            },
        ),
        migrations.CreateModel(
            name='ExpanseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField(default=1551)),
                ('leader_expense', models.IntegerField()),
                ('tour', models.IntegerField()),
                ('board_members', models.IntegerField()),
                ('admin_expense', models.IntegerField()),
                ('social_work', models.IntegerField()),
                ('misc', models.IntegerField()),
                ('product_cost', models.IntegerField()),
                ('karykarta_fund', models.IntegerField()),
                ('ngo_reserve_fund', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=1)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngojsct_mlm.membermodel')),
            ],
            options={
                'db_table': 'tbl_expense',
            },
        ),
        migrations.CreateModel(
            name='FundDistributionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=1)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngojsct_mlm.membermodel')),
            ],
            options={
                'db_table': 'tbl_fund_distri',
            },
        ),
        migrations.CreateModel(
            name='LevelIncomeDistributionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
                ('income', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=1)),
                ('referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referees', to='ngojsct_mlm.membermodel')),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='ngojsct_mlm.membermodel')),
            ],
            options={
                'db_table': 'tbl_level_income',
            },
        ),
    ]
