# Generated by Django 5.0.7 on 2025-06-17 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngojsct_mlm', '0002_donationsmodel_expansemodel_funddistributionmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationsmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='donationsmodel',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='donationsmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
