# Generated by Django 5.0.7 on 2025-06-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngojsct_mlm', '0003_donationsmodel_created_at_donationsmodel_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationsmodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
