# Generated by Django 5.0.7 on 2025-06-25 05:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngojsct_mlm', '0004_alter_donationsmodel_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credited', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('debited', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=1)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngojsct_mlm.membermodel')),
            ],
            options={
                'db_table': 'tbl_wallet',
            },
        ),
    ]
