# Generated by Django 5.0.7 on 2025-07-15 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngojsct_mlm', '0005_walletmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermodel',
            name='user_type',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='PaymentRequestDetailsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_text', models.TextField()),
                ('success_status', models.BooleanField()),
                ('payment_gatway_name', models.CharField(max_length=50)),
                ('method_type', models.CharField(max_length=50)),
                ('checksum', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attempts', models.IntegerField()),
                ('pay_for', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('is_indian', models.BooleanField(default=True)),
                ('order_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ngojsct_mlm.membermodel')),
            ],
            options={
                'db_table': 'tbl_payment_requets_det',
            },
        ),
        migrations.CreateModel(
            name='PaymentResponseDetailsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_text', models.TextField()),
                ('razorpay_payment_id', models.CharField(max_length=200)),
                ('razorpay_order_id', models.CharField(max_length=200)),
                ('razorpay_signature', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ngojsct_mlm.membermodel')),
            ],
            options={
                'db_table': 'tbl_payment_response_det',
            },
        ),
    ]
