# Generated by Django 5.0.7 on 2025-07-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngojsct_mlm', '0006_alter_membermodel_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermodel',
            name='mode_of_payment',
            field=models.CharField(blank=True, choices=[('Offline', 'Offline'), ('Online', 'Online')], max_length=50, null=True),
        ),
    ]
