# Generated by Django 5.0.7 on 2025-07-19 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngojsct_mlm', '0007_membermodel_mode_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletmodel',
            name='member_activated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_activated_by', to='ngojsct_mlm.membermodel'),
        ),
        migrations.AddField(
            model_name='walletmodel',
            name='member_whom_activated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_whom_activated', to='ngojsct_mlm.membermodel'),
        ),
    ]
